name: CI
on: push

jobs:
  Explore-directory-structure:
    runs-on: ubuntu-latest
    steps:
    - run: find /home/runner/work -maxdepth 3 2>/dev/null
    - run: find /home/runner -name .git 2>/dev/null
    - run: find /home/runner -maxdepth 2 -type d 2>/dev/null
    - run: find /home/runner -name README.md 2>/dev/null | grep -ve /runners/

  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code (in ${{ github.workspace }}) on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
